use_gpu: true 
save_masks: true
image_extension: ".jpg"
device: "cuda"  # Options: "cuda", "cpu", "mps"

# Paths
data_dir: "./sample_data/raw" # Raw data images dir path
output_dir: "./masks" # Path to output dir for masks

# Models
segmentation_model: "./models/cellpose_model" # Pretrained cellpose model path, setting this to an invalid path defaults cellpose to CPSAM
extraction_model: "./models/representation_learning_04_28.pth" # Pretrained extraction model path, setting this to an invalid path defaults cellpose to CPSAM
inference_batch: 1

# Tells us how to combine the 4 different images into 1
offset: 2304